# Generated by Django 5.2.14 on 2026-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_coupon_order_coupon_code_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Obuna', 'verbose_name_plural': 'Obunalar'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', "To'lov kutilmoqda"), ('AWAITING_APPROVAL', 'Tasdiqlash kutilmoqda'), ('PAID', "To'lov qabul qilindi"), ('IN_PROGRESS', 'Jarayonda'), ('DELIVERED', 'Yetkazildi'), ('COMPLETED', 'Yakunlandi'), ('CANCELLED', 'Bekor qilindi'), ('REFUNDED', 'Qaytarildi')], default='PENDING', max_length=20),
        ),
    ]
