# Generated by Django 5.1.15 on 2026-06-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit jurnali', 'verbose_name_plural': 'Audit jurnallari'},
        ),
        migrations.AlterModelOptions(
            name='blockedip',
            options={'verbose_name': 'Bloklangan IP', 'verbose_name_plural': 'Bloklangan IP manzillar'},
        ),
        migrations.AlterModelOptions(
            name='securitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Xavfsizlik jurnali', 'verbose_name_plural': 'Xavfsizlik jurnallari'},
        ),
    ]
