# Generated by Django 5.1.15 on 2026-06-26 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='sellers/avatars/%Y/%m/')),
                ('bio', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('new_seller', 'New Seller'), ('verified', 'Verified Seller'), ('professional', 'Professional Seller'), ('top_seller', 'Top Seller'), ('elite', 'Elite Seller')], default='new_seller', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('total_products', models.IntegerField(default=0)),
                ('active_products', models.IntegerField(default=0)),
                ('total_sales', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withdrawn_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_rating', models.FloatField(default=5.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('five_star_count', models.IntegerField(default=0)),
                ('four_star_count', models.IntegerField(default=0)),
                ('three_star_count', models.IntegerField(default=0)),
                ('two_star_count', models.IntegerField(default=0)),
                ('one_star_count', models.IntegerField(default=0)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Profile',
                'verbose_name_plural': 'Seller Profiles',
                'ordering': ['-total_sales', '-average_rating'],
            },
        ),
        migrations.CreateModel(
            name='ProductModeration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active & Visible'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('hidden', 'Hidden by Admin'), ('featured', 'Featured Product')], default='pending_review', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Feedback from admin to seller')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('admin_notes', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='videos.video')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_products', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_moderations', to='sellers.sellerprofile')),
            ],
            options={
                'verbose_name': 'Product Moderation',
                'verbose_name_plural': 'Product Moderations',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], help_text='1-5 star rating')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Only allow verified purchases')),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Product being reviewed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.video')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sellers.sellerprofile')),
            ],
            options={
                'verbose_name': 'Seller Review',
                'verbose_name_plural': 'Seller Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('app_approved', 'Application Approved'), ('app_rejected', 'Application Rejected'), ('changes_requested', 'Changes Requested'), ('prod_approved', 'Product Approved'), ('prod_rejected', 'Product Rejected'), ('prod_sold', 'Product Sold'), ('new_review', 'New Review Received'), ('suspended', 'Account Suspended'), ('banned', 'Account Banned')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.video')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sellers.sellerprofile')),
                ('related_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sellers.sellerreview')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_details', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='sellers.sellerprofile')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('telegram_username', models.CharField(help_text='Telegram username (without @)', max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('short_bio', models.TextField(help_text='Brief description of yourself and your business', max_length=500)),
                ('experience', models.TextField(help_text='Your relevant experience and background', max_length=1000)),
                ('what_will_sell', models.TextField(help_text='What products/services will you offer?', max_length=1000)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('passport_id_image', models.ImageField(blank=True, help_text='ID/Passport image for verification', null=True, upload_to='sellers/documents/%Y/%m/')),
                ('avatar', models.ImageField(blank=True, help_text='Profile avatar', null=True, upload_to='sellers/avatars/%Y/%m/')),
                ('agreement_accepted', models.BooleanField(default=False, help_text='User accepts terms & conditions')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('suspended', 'Suspended'), ('banned', 'Permanently Banned')], default='draft', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection/suspended/banned status')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Application',
                'verbose_name_plural': 'Seller Applications',
                'ordering': ['-submitted_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='sellers_sel_status_9fca6a_idx'), models.Index(fields=['user'], name='sellers_sel_user_id_2a6e36_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['level', '-total_sales'], name='sellers_sel_level_1f54db_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['is_verified', '-average_rating'], name='sellers_sel_is_veri_852120_idx'),
        ),
        migrations.AddIndex(
            model_name='productmoderation',
            index=models.Index(fields=['status', '-submitted_at'], name='sellers_pro_status_4d9a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='productmoderation',
            index=models.Index(fields=['seller', 'status'], name='sellers_pro_seller__2259af_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerreview',
            index=models.Index(fields=['seller', '-created_at'], name='sellers_sel_seller__d1be05_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerreview',
            index=models.Index(fields=['rating'], name='sellers_sel_rating_0a9915_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerreview',
            unique_together={('seller', 'buyer', 'product')},
        ),
        migrations.AddIndex(
            model_name='sellernotification',
            index=models.Index(fields=['seller', 'is_read'], name='sellers_sel_seller__4a3d54_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['seller', 'status'], name='sellers_wit_seller__a937b0_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', '-requested_at'], name='sellers_wit_status_f96d68_idx'),
        ),
    ]
