# Generated by Django on 2026-05-11

from django.db import migrations, models
from django.utils.text import slugify


def generate_unique_slug(apps, schema_editor):
    Product = apps.get_model('marketplace', 'Product')
    for product in Product.objects.all():
        if not product.slug:
            slug_base = slugify(product.title)
            slug = slug_base
            counter = 1
            while Product.objects.filter(slug=slug).exclude(pk=product.pk).exists():
                slug = f"{slug_base}-{counter}"
                counter += 1
            product.slug = slug
            product.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(generate_unique_slug, reverse_code=migrations.RunPython.noop),
    ]
