# Generated by Django 5.1.15 on 2026-06-08 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='marketplace.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide icon name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PHYSICAL', 'Jismoniy mahsulot'), ('DIGITAL', 'Raqamli mahsulot'), ('VIDEO_COURSE', 'Video kurs'), ('EBOOK', 'E-kitob (PDF)'), ('SOFTWARE', 'Dastur'), ('SERVICE', 'Xizmat'), ('SOURCE_CODE', 'Source Code'), ('MOBILE_APP', 'Mobil ilova'), ('PLUGIN', 'Plugin')], max_length=20),
        ),
    ]
