# Generated by Django 5.1.15 on 2026-06-11 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_category_parent_alter_category_icon_and_more'),
        ('videos', '0005_remove_lessonprogress_lesson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_wishlists', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='videos.video')),
            ],
            options={
                'verbose_name': 'Video istaklar',
                'verbose_name_plural': 'Video istaklar',
                'unique_together': {('user', 'video')},
            },
        ),
    ]
