# Generated by Django 5.1.15 on 2026-06-23 14:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPaymentCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=50)),
                ('card_holder', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Payment Card',
                'verbose_name_plural': 'Telegram Payment Cards',
            },
        ),
        migrations.CreateModel(
            name='TelegramProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField(blank=True, help_text='Stars count or months for Premium', null=True)),
                ('unit', models.CharField(default='stars', help_text='stars, months, gift_count', max_length=50)),
                ('price_uzs', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, upload_to='telegram_services/products/')),
                ('icon', models.CharField(default='⭐', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('delivery_type', models.CharField(choices=[('instant', 'Instant'), ('scheduled', 'Scheduled')], default='instant', max_length=50)),
                ('auto_delivery', models.BooleanField(default=True)),
                ('delivery_api_method', models.CharField(default='send_stars', help_text='API method name', max_length=100)),
                ('stock', models.IntegerField(default=-1, help_text='-1 for unlimited')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Product',
                'verbose_name_plural': 'Telegram Products',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('stars', 'Telegram Stars'), ('premium', 'Telegram Premium'), ('gifts', 'Telegram Gifts')], max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='⭐', max_length=50)),
                ('color', models.CharField(default='#FFC300', help_text='Hex color code', max_length=7)),
            ],
            options={
                'verbose_name': 'Telegram Product Category',
                'verbose_name_plural': 'Telegram Product Categories',
            },
        ),
        migrations.CreateModel(
            name='TelegramOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_username', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^@?\\w{5,32}$', 'Invalid Telegram username')])),
                ('telegram_user_id', models.CharField(blank=True, max_length=20)),
                ('telegram_avatar', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('waiting_payment', 'Waiting Payment'), ('waiting_confirmation', 'Waiting Confirmation'), ('paid', 'Paid'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='new', max_length=25)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unique_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unique_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('payment_method', models.CharField(default='card_transfer', max_length=50)),
                ('payment_screenshot', models.ImageField(blank=True, upload_to='telegram_services/payments/')),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('provider_response', models.JSONField(blank=True, null=True)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_orders', to=settings.AUTH_USER_MODEL)),
                ('payment_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_services.telegrampaymentcard')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram_services.telegramproduct')),
            ],
            options={
                'verbose_name': 'Telegram Order',
                'verbose_name_plural': 'Telegram Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='telegramproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='telegram_services.telegramproductcategory'),
        ),
        migrations.CreateModel(
            name='TelegramProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('fragmently', 'Fragmently'), ('custom', 'Custom API')], max_length=100)),
                ('api_token', models.CharField(help_text='API Token/Key for the provider', max_length=500)),
                ('wallet_version', models.CharField(default='v1', help_text='API Wallet Version', max_length=50)),
                ('payment_method', models.CharField(default='stars', help_text='Payment method type', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_test', models.BooleanField(default=False, help_text='Test mode')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('stars_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('premium_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Provider',
                'verbose_name_plural': 'Telegram Providers',
                'indexes': [models.Index(fields=['is_active', 'name'], name='telegram_se_is_acti_7dd8ec_idx')],
            },
        ),
        migrations.AddField(
            model_name='telegramproduct',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_services.telegramprovider'),
        ),
        migrations.CreateModel(
            name='TelegramGift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='telegram_services/gifts/')),
                ('price_uzs', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('provider_gift_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_services.telegramprovider')),
            ],
            options={
                'verbose_name': 'Telegram Gift',
                'verbose_name_plural': 'Telegram Gifts',
            },
        ),
        migrations.CreateModel(
            name='TelegramProviderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=100)),
                ('endpoint', models.URLField()),
                ('request_data', models.JSONField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_services.telegramorder')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='telegram_services.telegramprovider')),
            ],
            options={
                'verbose_name': 'Telegram Provider Log',
                'verbose_name_plural': 'Telegram Provider Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_enabled', models.BooleanField(default=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=15)),
                ('max_order_amount', models.DecimalField(decimal_places=2, default=50000000, max_digits=15)),
                ('payment_confirmation_timeout', models.IntegerField(default=3600, help_text='Seconds')),
                ('auto_delivery_enabled', models.BooleanField(default=True)),
                ('max_delivery_retries', models.IntegerField(default=3)),
                ('delivery_retry_interval', models.IntegerField(default=300, help_text='Seconds')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('support_email', models.EmailField(default='support@Digsell.uz', max_length=254)),
                ('support_telegram', models.CharField(default='@digsell_support', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram_services.telegramsettings')),
            ],
            options={
                'verbose_name': 'Telegram Settings',
                'verbose_name_plural': 'Telegram Settings',
            },
        ),
        migrations.CreateModel(
            name='TelegramNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('order_created', 'Order Created'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('delivery_processing', 'Delivery Processing'), ('delivery_completed', 'Delivery Completed'), ('delivery_failed', 'Delivery Failed'), ('refund_issued', 'Refund Issued')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notifications', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='telegram_services.telegramorder')),
            ],
            options={
                'verbose_name': 'Telegram Notification',
                'verbose_name_plural': 'Telegram Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='telegram_se_user_id_ac199e_idx'), models.Index(fields=['notification_type'], name='telegram_se_notific_d7f62c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramOrderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('status_from', models.CharField(blank=True, max_length=25)),
                ('status_to', models.CharField(blank=True, max_length=25)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='telegram_services.telegramorder')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Order Log',
                'verbose_name_plural': 'Telegram Order Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='telegram_se_order_i_cabd04_idx'), models.Index(fields=['action'], name='telegram_se_action_18036e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=25)),
                ('payment_method', models.CharField(default='card_transfer', max_length=50)),
                ('payment_details', models.JSONField(blank=True, null=True)),
                ('confirmation_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='telegram_services.telegramorder')),
            ],
            options={
                'verbose_name': 'Telegram Payment',
                'verbose_name_plural': 'Telegram Payments',
                'indexes': [models.Index(fields=['payment_status', 'created_at'], name='telegram_se_payment_0511b5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='telegramorder',
            index=models.Index(fields=['user', 'status'], name='telegram_se_user_id_4bc9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramorder',
            index=models.Index(fields=['telegram_username'], name='telegram_se_telegra_4bbab4_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramorder',
            index=models.Index(fields=['unique_code'], name='telegram_se_unique__4b6f26_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramorder',
            index=models.Index(fields=['status', 'created_at'], name='telegram_se_status_ec3046_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramproduct',
            index=models.Index(fields=['category', 'status'], name='telegram_se_categor_2fe6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramproduct',
            index=models.Index(fields=['sku'], name='telegram_se_sku_23607c_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramproduct',
            index=models.Index(fields=['created_at'], name='telegram_se_created_4c4547_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramproviderlog',
            index=models.Index(fields=['provider', 'created_at'], name='telegram_se_provide_6ecbb0_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramproviderlog',
            index=models.Index(fields=['status_code'], name='telegram_se_status__3b42a0_idx'),
        ),
    ]
