# Generated by Django 5.1.15 on 2026-06-25 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegramorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegramnotification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='telegram_services.telegramorder'),
        ),
        migrations.AddField(
            model_name='telegramorderlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='telegram_services.telegramorder'),
        ),
        migrations.AddField(
            model_name='telegramorderlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegrampayment',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegrampayment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='telegram_services.telegramorder'),
        ),
        migrations.AddField(
            model_name='telegramorder',
            name='payment_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_services.telegrampaymentcard'),
        ),
        migrations.AddField(
            model_name='telegramproduct',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegramorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram_services.telegramproduct'),
        ),
        migrations.AddField(
            model_name='telegramproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='telegram_services.telegramproductcategory'),
        ),
        migrations.AddIndex(
            model_name='telegramprovider',
            index=models.Index(fields=['is_active', 'name'], name='telegram_se_is_acti_7dd8ec_idx'),
        ),
        migrations.AddField(
            model_name='telegramproduct',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_services.telegramprovider'),
        ),
        migrations.AddField(
            model_name='telegramgift',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_services.telegramprovider'),
        ),
        migrations.AddField(
            model_name='telegramproviderlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_services.telegramorder'),
        ),
        migrations.AddField(
            model_name='telegramproviderlog',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='telegram_services.telegramprovider'),
        ),
        migrations.AddIndex(
            model_name='telegramnotification',
            index=models.Index(fields=['user', 'is_read'], name='telegram_se_user_id_ac199e_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramnotification',
            index=models.Index(fields=['notification_type'], name='telegram_se_notific_d7f62c_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramorderlog',
            index=models.Index(fields=['order', 'created_at'], name='telegram_se_order_i_cabd04_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramorderlog',
            index=models.Index(fields=['action'], name='telegram_se_action_18036e_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrampayment',
            index=models.Index(fields=['payment_status', 'created_at'], name='telegram_se_payment_0511b5_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramorder',
            index=models.Index(fields=['user', 'status'], name='telegram_se_user_id_4bc9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramorder',
            index=models.Index(fields=['telegram_username'], name='telegram_se_telegra_4bbab4_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramorder',
            index=models.Index(fields=['unique_code'], name='telegram_se_unique__4b6f26_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramorder',
            index=models.Index(fields=['status', 'created_at'], name='telegram_se_status_ec3046_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramproduct',
            index=models.Index(fields=['category', 'status'], name='telegram_se_categor_2fe6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramproduct',
            index=models.Index(fields=['sku'], name='telegram_se_sku_23607c_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramproduct',
            index=models.Index(fields=['created_at'], name='telegram_se_created_4c4547_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramproviderlog',
            index=models.Index(fields=['provider', 'created_at'], name='telegram_se_provide_6ecbb0_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramproviderlog',
            index=models.Index(fields=['status_code'], name='telegram_se_status__3b42a0_idx'),
        ),
    ]
