"""Remove payment_screenshot field from TelegramOrder model.

Generated by automated assistant.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_services', '0003_reward_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramorder',
            name='payment_screenshot',
        ),
    ]
