# Generated by Django 5.1.15 on 2026-06-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='gifts_message_template',
            field=models.TextField(default='━━━━━━━━━━━━━━\n🎁 GIFT PURCHASE REQUEST\n━━━━━━━━━━━━━━\n\n👤 User: @{username}\n\n🎁 Gift:\n{gift_name}\n\n💰 Price:\n{price} UZS\n\n🆔 Product ID:\n#{product_id}\n\n📅 Date:\n{current_date}\n\n🌐 Source:\nDigsell.uz\n\n━━━━━━━━━━━━━━\n\nAssalomu alaykum.\n\nMen ushbu giftni sotib olmoqchiman.\nIltimos, xarid jarayonini boshlashga yordam bering.\n\nRahmat.', help_text='Template for pre-filled Telegram message'),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='gifts_redirect_enabled',
            field=models.BooleanField(default=True, help_text='Enable/Disable redirecting to Telegram for Gifts'),
        ),
        migrations.AddField(
            model_name='telegramsettings',
            name='gifts_telegram_username',
            field=models.CharField(default='@slx15', help_text='Destination Telegram username for Gifts purchase redirect', max_length=100),
        ),
    ]
