# Generated by Django 5.1.15 on 2026-06-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_services', '0002_telegramsettings_gifts_message_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramproductcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='telegram_services/categories/', verbose_name='Category default image'),
        ),
    ]
