# Generated by GitHub Copilot on 2026-06-25

import uuid
from datetime import timedelta
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def create_initial_reward_campaign(apps, schema_editor):
    TelegramRewardCampaign = apps.get_model('telegram_services', 'TelegramRewardCampaign')
    TelegramRewardStage = apps.get_model('telegram_services', 'TelegramRewardStage')

    now = timezone.now()
    campaign = TelegramRewardCampaign.objects.create(
        name='Sovrin Yo‘li: Telegram Bonus Yo‘li',
        description='Telegram Stars va Premium xaridlaringiz uchun sodiqlik yo‘li. Har bir bosqichda qo‘shimcha bonuslar va chegirmalar kutmoqda.',
        highlight_text='Telegram xaridlari orqali sodiqlik hosil qiling va bonuslar oling.',
        is_active=True,
        start_date=now,
        end_date=now + timedelta(days=90),
    )

    stages = [
        {
            'position': 1,
            'title': 'Bronze Start',
            'description': 'Telegram bo‘yicha ilk 50,000 UZS sarflang va boshlang‘ich bonusni qo‘lga kiriting.',
            'target_type': 'total_spent',
            'target_value': 50000,
            'reward_type': 'bonus_balance',
            'reward_amount': 10000,
            'reward_description': '10,000 UZS bonus balans',
        },
        {
            'position': 2,
            'title': 'Stars Master',
            'description': '200 Stars xaridingizdan so‘ng qo‘shimcha ballar va sovrin oling.',
            'target_type': 'stars_purchased',
            'target_value': 200,
            'reward_type': 'bonus_points',
            'reward_amount': 125,
            'reward_description': '125 bonus ball',
        },
        {
            'position': 3,
            'title': 'Premium Pro',
            'description': 'Premium obunalaringizdan 1 oy to‘plang va keyingi xarid uchun cashback oling.',
            'target_type': 'premium_months',
            'target_value': 1,
            'reward_type': 'cashback',
            'reward_amount': 5000,
            'reward_description': '5,000 UZS cashback',
        },
        {
            'position': 4,
            'title': 'Elite Reward',
            'description': 'Telegram sotuvlaringiz 200,000 UZSga yetganda eksklyuziv chegirma kodini qo‘lga kiriting.',
            'target_type': 'total_spent',
            'target_value': 200000,
            'reward_type': 'discount_code',
            'reward_amount': 0,
            'reward_description': 'TGLOYAL20 chegirma kodi',
        },
    ]

    for stage_data in stages:
        TelegramRewardStage.objects.create(campaign=campaign, **stage_data)


def remove_initial_reward_campaign(apps, schema_editor):
    TelegramRewardCampaign = apps.get_model('telegram_services', 'TelegramRewardCampaign')
    TelegramRewardCampaign.objects.filter(name='Sovrin Yo‘li: Telegram Bonus Yo‘li').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramRewardCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('highlight_text', models.CharField(blank=True, max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='telegram_services/rewards/')), 
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Reward Campaign',
                'verbose_name_plural': 'Telegram Reward Campaigns',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramRewardStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('target_type', models.CharField(choices=[('total_spent', 'Telegram spend (UZS)'), ('stars_purchased', 'Telegram Stars purchased'), ('premium_months', 'Telegram Premium months')], default='total_spent', max_length=30)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=15, default=0)),
                ('reward_type', models.CharField(choices=[('bonus_balance', 'Bonus Balance'), ('cashback', 'Cashback'), ('bonus_points', 'Bonus Points'), ('discount_code', 'Discount Voucher'), ('manual_reward', 'Manual Reward')], default='bonus_balance', max_length=30)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=12, default=0)),
                ('reward_description', models.CharField(blank=True, max_length=220)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='telegram_services.telegramrewardcampaign')),
            ],
            options={
                'verbose_name': 'Telegram Reward Stage',
                'verbose_name_plural': 'Telegram Reward Stages',
                'ordering': ['campaign', 'position'],
            },
        ),
        migrations.CreateModel(
            name='TelegramRewardClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=20)),
                ('reward_type', models.CharField(choices=[('bonus_balance', 'Bonus Balance'), ('cashback', 'Cashback'), ('bonus_points', 'Bonus Points'), ('discount_code', 'Discount Voucher'), ('manual_reward', 'Manual Reward')], max_length=30)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=12, default=0)),
                ('reward_description', models.CharField(blank=True, max_length=220)),
                ('reward_granted', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_claims', to='telegram_services.telegramrewardcampaign')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='telegram_services.telegramrewardstage')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reward_claims', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_reward_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Reward Claim',
                'verbose_name_plural': 'Telegram Reward Claims',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='telegramrewardclaim',
            constraint=models.UniqueConstraint(fields=['user', 'stage'], name='unique_user_reward_stage'),
        ),
        migrations.AddIndex(
            model_name='telegramrewardstage',
            index=models.Index(fields=['campaign', 'target_type'], name='telegram_se_campaig_539bc8_idx'),
        ),
        migrations.RunPython(create_initial_reward_campaign, reverse_code=remove_initial_reward_campaign),
    ]
