# Generated by Django 5.1.15 on 2026-06-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_services', '0003_telegramproductcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramorder',
            name='custom_quantity',
            field=models.IntegerField(blank=True, help_text='Override product quantity for custom orders', null=True),
        ),
    ]
