# Generated by Django 5.1.15 on 2026-06-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_services', '0005_telegramproduct_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramproduct',
            name='is_resale',
            field=models.BooleanField(default=False, help_text='Show Resale ribbon'),
        ),
        migrations.AddField(
            model_name='telegramproduct',
            name='price_stars',
            field=models.IntegerField(blank=True, help_text='Price in Telegram Stars', null=True),
        ),
        migrations.AddField(
            model_name='telegramproduct',
            name='rarity',
            field=models.CharField(blank=True, choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20, null=True),
        ),
    ]
