# Generated by Django 5.1.15 on 2026-06-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_services', '0006_telegramproduct_is_resale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsettings',
            name='instance',
        ),
    ]
