# Generated by Django 5.1.15 on 2026-06-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='demo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='moderation_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='moderation_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested'), ('SUSPENDED', 'Suspended')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='seo_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
