# Generated by Django 5.1.15 on 2026-06-08 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_enterprise_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='lesson',
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Categories (Tree)'},
        ),
        migrations.AlterModelOptions(
            name='videoreview',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='video',
            name='purchases_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
        migrations.AlterUniqueTogether(
            name='videopurchase',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='videoreview',
            unique_together={('user', 'product')},
        ),
        migrations.AddField(
            model_name='video',
            name='avg_rating',
            field=models.DecimalField(db_column='rating', decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='video',
            name='sales_count',
            field=models.PositiveIntegerField(db_column='purchases_count', default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='views_count',
            field=models.PositiveIntegerField(db_column='views', default=0),
        ),
        migrations.AddField(
            model_name='videopurchase',
            name='product',
            field=models.ForeignKey(blank=True, db_column='video_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
        ),
        migrations.AddField(
            model_name='videoreview',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='icon',
            field=models.CharField(default='fas fa-folder', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to='previews/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='videopurchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='videopurchase',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='videopurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonProgress',
        ),
        migrations.RemoveField(
            model_name='videopurchase',
            name='video',
        ),
        migrations.RemoveField(
            model_name='videoreview',
            name='video',
        ),
    ]
