# Generated by Django 5.1.15 on 2026-06-16 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_lessonprogress_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoreview',
            name='product',
            field=models.ForeignKey(blank=True, db_column='video_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='videos.video'),
        ),
    ]
