# Generated by Django 5.1.15 on 2026-06-26 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HamyonPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider', models.CharField(default='HAMYON', max_length=50)),
                ('card', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('SUCCESS', 'Tasdiqlandi'), ('FAILED', 'Xatolik'), ('CANCELLED', 'Bekor qilingan'), ('EXPIRED', "Muddati o'tgan")], default='PENDING', max_length=20)),
                ('external_data', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='hamyon_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Hamyon to'lovi",
                'verbose_name_plural': "Hamyon to'lovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
