# Generated by Django 5.1.15 on 2026-06-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_hamyon_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamyonpayment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hamyonpayment',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hamyonpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hamyonpayment',
            name='purpose',
            field=models.CharField(choices=[('WALLET_TOPUP', "Balans to'ldirish"), ('MARKETPLACE_ORDER', 'Marketplace buyurtmasi'), ('TELEGRAM_ORDER', 'Telegram buyurtmasi'), ('VIDEO_PURCHASE', 'Digital mahsulot'), ('OTHER', 'Boshqa')], default='WALLET_TOPUP', max_length=30),
        ),
        migrations.AddField(
            model_name='hamyonpayment',
            name='purpose_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
