# Generated by Django 5.1.15 on 2026-06-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_hamyonpayment_description_hamyonpayment_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamyonpayment',
            name='payment_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hamyonpayment',
            name='requested_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
