# Generated by Django 5.1.15 on 2026-05-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_withdrawalrequest_card_number_usercard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, verbose_name='Karta raqami')),
                ('card_name', models.CharField(help_text='Masalan: Uzcard, Humo, Visa', max_length=50, verbose_name='Karta turi')),
                ('card_holder', models.CharField(max_length=100, verbose_name='Karta egasi')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
