# Generated by Django 5.1.15 on 2026-06-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_coupon_couponusage_couponvalidationattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycard',
            options={'verbose_name': 'Kompaniya kartasi', 'verbose_name_plural': 'Kompaniya kartalari'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kupon', 'verbose_name_plural': 'Kuponlar'},
        ),
        migrations.AlterModelOptions(
            name='couponusage',
            options={'verbose_name': 'Kupon ishlatilishi', 'verbose_name_plural': 'Kupon ishlatilishi'},
        ),
        migrations.AlterModelOptions(
            name='couponvalidationattempt',
            options={'verbose_name': 'Kupon tekshiruvi', 'verbose_name_plural': 'Kupon tekshiruvlari'},
        ),
        migrations.AlterModelOptions(
            name='escrowaccount',
            options={'verbose_name': 'Hamyon', 'verbose_name_plural': 'Hamyonlar'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tranzaksiya', 'verbose_name_plural': 'Tranzaksiyalar'},
        ),
        migrations.AlterModelOptions(
            name='usercard',
            options={'verbose_name': 'Foydalanuvchi kartasi', 'verbose_name_plural': 'Foydalanuvchi kartalari'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-created_at'], 'verbose_name': "Pul yechish so'rovi", 'verbose_name_plural': "Pul yechish so'rovlari"},
        ),
    ]
