# Generated by Django 5.1.15 on 2026-06-24 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_companycard_options_alter_coupon_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='deposit_receipts/')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('APPROVED', 'Tasdiqlandi'), ('REJECTED', 'Rad etildi')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Balans to'ldirish so'rovi",
                'verbose_name_plural': "Balans to'ldirish so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
