# Generated by Django 5.1.15 on 2026-06-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('TOPUP', 'Top-up'), ('PURCHASE', 'Purchase'), ('REFUND', 'Refund'), ('ADMIN', 'Admin'), ('TRANSFER', 'Transfer'), ('BONUS', 'Bonus')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
