# Generated by Django 5.2.14 on 2026-05-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Kuzatuv', 'verbose_name_plural': 'Kuzatuvlar'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Foydalanuvchi faoliyati', 'verbose_name_plural': 'Foydalanuvchilar faoliyati'},
        ),
        migrations.AddField(
            model_name='user',
            name='badge',
            field=models.CharField(choices=[('NONE', 'Oddiy'), ('VERIFIED', 'Tasdiqlangan ✓'), ('PREMIUM', 'Premium ⭐'), ('TRUSTED', 'Ishonchli 🛡️'), ('TOP_SELLER', 'Top Seller 🏆')], default='NONE', max_length=20),
        ),
    ]
