# Generated by Django 5.2.14 on 2026-05-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_follow_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_saved_card',
            field=models.BooleanField(default=False),
        ),
    ]
