# Generated by Django 5.1.15 on 2026-06-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('ad_type', models.CharField(choices=[('BANNER', 'Banner'), ('CARD', 'Reklama karta'), ('POPUP', 'Popup')], default='CARD', max_length=20)),
                ('placement', models.CharField(choices=[('HOME', 'Bosh sahifa'), ('MARKETPLACE', 'Marketplace'), ('COURSES', 'Video kurslar'), ('SIDEBAR', 'Yon panel'), ('GLOBAL', 'Barcha sahifalar')], default='GLOBAL', max_length=20)),
                ('bg_color', models.CharField(blank=True, default='#0ea5e9', max_length=20)),
                ('text_color', models.CharField(blank=True, default='#ffffff', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_from', models.DateTimeField(blank=True, null=True)),
                ('show_until', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('banner_type', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobil'), ('SLIDER', 'Slider')], default='SLIDER', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Xariddan beriladigan bonus foizi', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('comp_type', models.CharField(choices=[('TOP_BUYER', 'Top Xaridor'), ('TOP_SELLER', 'Top Sotuvchi'), ('TOP_REFERRAL', 'Top Referral'), ('TOP_SPENDER', 'Top Spender')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kunlik bonus',
                'verbose_name_plural': 'Kunlik bonuslar',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(default=100)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('prize_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('image', models.ImageField(upload_to='marketing/rewards/')),
            ],
        ),
        migrations.CreateModel(
            name='SpinWheelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpinWheelPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prize_type', models.CharField(choices=[('BONUS', 'Bonus pul'), ('CASHBACK', 'Extra Cashback'), ('PROMO', 'Promokod'), ('FREE_VIDEO', 'Bepul video'), ('NONE', "Yana bir bor urinib ko'ring")], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing/prizes/')),
                ('probability', models.FloatField(help_text='Sovrin chiqish ehtimoli (0-100)')),
            ],
        ),
    ]
