# Generated by Django 5.1.15 on 2026-06-26 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0003_category_description_category_display_order_and_more'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Banner title (internal use)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Internal notes about this banner')),
                ('banner_type', models.CharField(choices=[('hero_slider', 'Hero Slider'), ('promotion', 'Promotion Banner'), ('card', 'Advertisement Card'), ('alert', 'Alert Banner'), ('carousel', 'Carousel Banner'), ('sidebar', 'Sidebar Banner'), ('category', 'Category Banner'), ('product', 'Product Banner'), ('marketplace', 'Marketplace Banner'), ('announcement', 'Announcement Banner'), ('discount', 'Discount Banner'), ('full_width', 'Full Width Banner'), ('inline', 'Inline Banner'), ('floating', 'Floating Banner'), ('popup', 'Popup Campaign')], default='hero_slider', help_text='Type of banner', max_length=30)),
                ('position', models.CharField(choices=[('top', 'Top of Page'), ('hero', 'Hero Section'), ('above_content', 'Above Content'), ('sidebar_top', 'Sidebar Top'), ('sidebar_middle', 'Sidebar Middle'), ('sidebar_bottom', 'Sidebar Bottom'), ('inline_content', 'Inline Content'), ('below_content', 'Below Content'), ('footer_top', 'Footer Top'), ('footer', 'Footer'), ('floating', 'Floating'), ('modal', 'Modal/Popup'), ('marketplace_top', 'Marketplace Top'), ('marketplace_sidebar', 'Marketplace Sidebar'), ('category_top', 'Category Top'), ('product_top', 'Product Top')], default='top', help_text='Where this banner appears', max_length=30)),
                ('heading', models.CharField(blank=True, help_text='Main heading text', max_length=200)),
                ('subheading', models.CharField(blank=True, help_text='Subheading text', max_length=300)),
                ('content', models.TextField(blank=True, help_text='Main content/description')),
                ('image', models.ImageField(blank=True, help_text='Main banner image (desktop)', null=True, upload_to='banners/%Y/%m/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Mobile-optimized image', null=True, upload_to='banners/mobile/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail for carousel/card', null=True, upload_to='banners/thumbnails/%Y/%m/')),
                ('cta_text', models.CharField(blank=True, default='Click Here', help_text='Button text', max_length=100)),
                ('cta_url', models.URLField(blank=True, help_text='Button link URL')),
                ('cta_target_blank', models.BooleanField(default=False, help_text='Open link in new tab')),
                ('background_color', models.CharField(blank=True, default='#0a0a1a', help_text='Background color (hex code)', max_length=7)),
                ('gradient', models.CharField(blank=True, help_text="CSS gradient (e.g., 'from-violet-500 to-indigo-600')", max_length=255)),
                ('text_color', models.CharField(blank=True, default='#ffffff', help_text='Text color (hex code)', max_length=7)),
                ('animation_style', models.CharField(blank=True, choices=[('fade', 'Fade In'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('slide-up', 'Slide Up'), ('slide-down', 'Slide Down'), ('scale', 'Scale'), ('bounce', 'Bounce'), ('pulse', 'Pulse'), ('glow', 'Glow')], default='fade', help_text='Animation style', max_length=50)),
                ('animation_duration', models.IntegerField(default=500, help_text='Animation duration in milliseconds')),
                ('alert_type', models.CharField(blank=True, choices=[('success', 'Success'), ('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('announcement', 'Announcement'), ('system', 'System Update'), ('maintenance', 'Maintenance'), ('promotion', 'Promotion')], default='info', help_text='Alert type (for alert banners)', max_length=20)),
                ('is_closable', models.BooleanField(default=True, help_text='Allow user to close alert')),
                ('discount_label', models.CharField(blank=True, help_text="Discount badge text (e.g., '50% OFF')", max_length=50)),
                ('has_countdown', models.BooleanField(default=False, help_text='Show countdown timer')),
                ('countdown_text', models.CharField(blank=True, default='Offer ends in', help_text='Countdown label', max_length=100)),
                ('start_date', models.DateTimeField(blank=True, help_text='When banner becomes active', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When banner expires', null=True)),
                ('device_target', models.CharField(choices=[('all', 'All Devices'), ('desktop', 'Desktop Only'), ('tablet', 'Tablet Only'), ('mobile', 'Mobile Only'), ('mobile_tablet', 'Mobile & Tablet'), ('desktop_tablet', 'Desktop & Tablet')], default='all', help_text='Target specific devices', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher = shown first (0-100)')),
                ('display_order', models.IntegerField(default=0, help_text='Order within same priority')),
                ('max_impressions', models.IntegerField(blank=True, help_text='Max times to show (leave empty for unlimited)', null=True)),
                ('current_impressions', models.IntegerField(default=0, editable=False, help_text='Current impression count')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', help_text='Banner status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advertisements', to=settings.AUTH_USER_MODEL)),
                ('target_category', models.ForeignKey(blank=True, help_text='Show only in this category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.category')),
                ('target_product', models.ForeignKey(blank=True, help_text='Show only for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.video')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-priority', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='advertisements.advertisement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertisement Click',
                'verbose_name_plural': 'Advertisement Clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=20)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='advertisements.advertisement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertisement Impression',
                'verbose_name_plural': 'Advertisement Impressions',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Group name (e.g., 'Homepage Hero Slider')", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('banner_type', models.CharField(choices=[('hero_slider', 'Hero Slider'), ('promotion', 'Promotion Banner'), ('card', 'Advertisement Card'), ('alert', 'Alert Banner'), ('carousel', 'Carousel Banner'), ('sidebar', 'Sidebar Banner'), ('category', 'Category Banner'), ('product', 'Product Banner'), ('marketplace', 'Marketplace Banner'), ('announcement', 'Announcement Banner'), ('discount', 'Discount Banner'), ('full_width', 'Full Width Banner'), ('inline', 'Inline Banner'), ('floating', 'Floating Banner'), ('popup', 'Popup Campaign')], help_text='Type of banners in this group', max_length=30)),
                ('position', models.CharField(choices=[('top', 'Top of Page'), ('hero', 'Hero Section'), ('above_content', 'Above Content'), ('sidebar_top', 'Sidebar Top'), ('sidebar_middle', 'Sidebar Middle'), ('sidebar_bottom', 'Sidebar Bottom'), ('inline_content', 'Inline Content'), ('below_content', 'Below Content'), ('footer_top', 'Footer Top'), ('footer', 'Footer'), ('floating', 'Floating'), ('modal', 'Modal/Popup'), ('marketplace_top', 'Marketplace Top'), ('marketplace_sidebar', 'Marketplace Sidebar'), ('category_top', 'Category Top'), ('product_top', 'Product Top')], help_text='Display position', max_length=30)),
                ('autoplay', models.BooleanField(default=True)),
                ('autoplay_delay', models.IntegerField(default=5000, help_text='Delay in milliseconds')),
                ('loop_enabled', models.BooleanField(default=True)),
                ('show_navigation', models.BooleanField(default=True)),
                ('show_indicators', models.BooleanField(default=True)),
                ('animation_duration', models.IntegerField(default=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banners', models.ManyToManyField(help_text='Banners in this group', related_name='groups', to='advertisements.advertisement')),
            ],
            options={
                'verbose_name': 'Banner Group',
                'verbose_name_plural': 'Banner Groups',
                'ordering': ['banner_type', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', '-priority'], name='advertiseme_status_02e5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['position', 'status'], name='advertiseme_positio_ab7f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['banner_type', 'status'], name='advertiseme_banner__914941_idx'),
        ),
    ]
