# Generated by Django 5.1.15 on 2026-06-25 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelance', '0002_initial'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='freelance.contest'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contest_won', to='freelance.contestsubmission'),
        ),
        migrations.AddField(
            model_name='freelanceauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancedispute',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_disputes_opened', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancedispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelance_disputes_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelanceescrowtransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelanceescrowtransaction',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrow_payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelanceescrowtransaction',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='escrow_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='freelance.freelanceescrowtransaction'),
        ),
        migrations.AddField(
            model_name='freelancefile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelanceinvoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_invoices_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelanceinvoice',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_invoices_freelancer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelanceproject',
            name='assigned_freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelanceproject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='freelanceproject',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelanceinvoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='freelance.freelanceproject'),
        ),
        migrations.AddField(
            model_name='freelancefile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='freelance.freelanceproject'),
        ),
        migrations.AddField(
            model_name='freelanceescrowtransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_transactions', to='freelance.freelanceproject'),
        ),
        migrations.AddField(
            model_name='freelancedispute',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='freelance.freelanceproject'),
        ),
        migrations.AddField(
            model_name='freelancecontract',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='freelance.freelanceproject'),
        ),
        migrations.AddField(
            model_name='freelancereview',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancereview',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='freelance.freelanceproject'),
        ),
        migrations.AddField(
            model_name='freelancereview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='freelance.freelancerprofile'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='escrow_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='freelance.freelanceescrowtransaction'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='freelance.freelanceproject'),
        ),
        migrations.AddField(
            model_name='freelanceinvoice',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='freelance.milestone'),
        ),
        migrations.AddField(
            model_name='freelanceescrowtransaction',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_payments', to='freelance.milestone'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='freelance.freelancerprofile'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='freelance.freelanceproject'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.category'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='skills',
            field=models.ManyToManyField(blank=True, to='freelance.skill'),
        ),
        migrations.AddField(
            model_name='freelancerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.skill'),
        ),
        migrations.AddField(
            model_name='freelanceproject',
            name='skills_required',
            field=models.ManyToManyField(blank=True, related_name='projects', to='freelance.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='contestsubmission',
            unique_together={('contest', 'freelancer')},
        ),
        migrations.AddIndex(
            model_name='freelanceauditlog',
            index=models.Index(fields=['action', '-created_at'], name='freelance_f_action_693310_idx'),
        ),
        migrations.AddIndex(
            model_name='freelanceauditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='freelance_f_model_n_001bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancereview',
            index=models.Index(fields=['freelancer', 'rating'], name='freelance_f_freelan_8cfa8d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='freelancereview',
            unique_together={('project', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['is_top_rated'], name='freelance_f_is_top__0b5bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['hourly_rate'], name='freelance_f_hourly__5350ed_idx'),
        ),
        migrations.AddIndex(
            model_name='freelanceescrowtransaction',
            index=models.Index(fields=['status', 'project'], name='freelance_f_status_2a0413_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['project', 'status'], name='freelance_p_project_a06867_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['freelancer', 'status'], name='freelance_p_freelan_7235db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together={('project', 'freelancer')},
        ),
        migrations.AlterUniqueTogether(
            name='freelancerskill',
            unique_together={('profile', 'skill')},
        ),
        migrations.AddIndex(
            model_name='freelanceproject',
            index=models.Index(fields=['status', '-created_at'], name='freelance_f_status_419c35_idx'),
        ),
        migrations.AddIndex(
            model_name='freelanceproject',
            index=models.Index(fields=['category', 'status'], name='freelance_f_categor_b753f7_idx'),
        ),
        migrations.AddIndex(
            model_name='freelanceproject',
            index=models.Index(fields=['budget'], name='freelance_f_budget_3b5d7f_idx'),
        ),
    ]
