# Generated by Django 5.1.15 on 2026-06-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0007_contest_contestsubmission_contest_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
