# Generated by Django 5.1.15 on 2026-06-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('ORDER_NEW', 'Yangi buyurtma'), ('ORDER_PAID', "To'lov tasdiqlandi"), ('ORDER_CANCELLED', 'Buyurtma bekor qilindi'), ('WITHDRAWAL_APPROVED', 'Yechib olish tasdiqlandi'), ('WITHDRAWAL_REJECTED', 'Yechib olish rad etildi'), ('SUPPORT_NEW', 'Yangi support ticket'), ('SUPPORT_REPLY', 'Admin javobi (support)'), ('FREELANCE_PROPOSAL_NEW', 'Yangi freelance taklif'), ('FREELANCE_PROPOSAL_ACCEPTED', 'Freelance taklif qabul qilindi'), ('FREELANCE_PROPOSAL_REJECTED', 'Freelance taklif rad etildi'), ('FREELANCE_MILESTONE_DUE', 'Milestone muddati'), ('FREELANCE_PAYMENT_PENDING', "Freelance to'lov kutilmoqda"), ('FREELANCE_ESCROW_RELEASED', "Escrow to'lov o'tkazildi")], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('target_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
