# Generated by Django 5.2.14 on 2026-05-10 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('ORDER_NEW', 'Yangi buyurtma'), ('ORDER_PAID', "To'lov tasdiqlandi"), ('ORDER_CANCELLED', 'Buyurtma bekor qilindi'), ('WITHDRAWAL_APPROVED', 'Yechib olish tasdiqlandi'), ('WITHDRAWAL_REJECTED', 'Yechib olish rad etildi')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
