# Generated by Django 5.1.15 on 2026-06-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('ORDER_NEW', 'Yangi buyurtma'), ('ORDER_PAID', "To'lov tasdiqlandi"), ('ORDER_CANCELLED', 'Buyurtma bekor qilindi'), ('WITHDRAWAL_APPROVED', 'Yechib olish tasdiqlandi'), ('WITHDRAWAL_REJECTED', 'Yechib olish rad etildi'), ('SUPPORT_NEW', 'Yangi support ticket'), ('SUPPORT_REPLY', 'Admin javobi (support)')], max_length=30),
        ),
    ]
