# Generated by Django 5.1.15 on 2026-06-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('ORDER_NEW', 'Yangi buyurtma'), ('ORDER_PAID', "To'lov tasdiqlandi"), ('ORDER_CANCELLED', 'Buyurtma bekor qilindi'), ('WITHDRAWAL_APPROVED', 'Yechib olish tasdiqlandi'), ('WITHDRAWAL_REJECTED', 'Yechib olish rad etildi'), ('WALLET_TOPUP', "Hamyon to'ldirildi"), ('WALLET_PAYMENT_FAILED', "Hamyon to'lovi xatolik bilan yakunlandi"), ('WALLET_PAYMENT_CANCELLED', "Hamyon to'lovi bekor qilindi"), ('SUPPORT_NEW', 'Yangi support ticket'), ('SUPPORT_REPLY', 'Admin javobi (support)'), ('FREELANCE_PROPOSAL_NEW', 'Yangi freelance taklif'), ('FREELANCE_PROPOSAL_ACCEPTED', 'Freelance taklif qabul qilindi'), ('FREELANCE_PROPOSAL_REJECTED', 'Freelance taklif rad etildi'), ('FREELANCE_MILESTONE_DUE', 'Milestone muddati'), ('FREELANCE_PAYMENT_PENDING', "Freelance to'lov kutilmoqda"), ('FREELANCE_ESCROW_RELEASED', "Escrow to'lov o'tkazildi")], max_length=30),
        ),
    ]
