# Generated by Django 5.1.15 on 2026-06-16 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('freelance', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='freelance_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='freelance.freelanceproject'),
        ),
    ]
